#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBF0B339C64BCAA8B (smartmontools-support@listi.jpberlin.de)
#
Name     : smartmontools
Version  : 7.1
Release  : 12
URL      : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.1/smartmontools-7.1.tar.gz
Source0  : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.1/smartmontools-7.1.tar.gz
Source1  : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.1/smartmontools-7.1.tar.gz.asc
Summary  : Control and monitor S.M.A.R.T. enabled ATA and SCSI Hard Drives
Group    : Development/Tools
License  : GPL-2.0
Requires: smartmontools-bin = %{version}-%{release}
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-man = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}
BuildRequires : libcap-ng-dev
BuildRequires : systemd-dev

%description
<html>
<body>
<h2>About this package</h2>
The smartmontools package contains two utility programs (smartctl and smartd) to control
and monitor storage systems using the Self-Monitoring, Analysis and Reporting
Technology System (SMART) built into most modern ATA and SCSI harddisks.
In many cases, these utilities will provide advanced warning of disk degradation and failure.
<h2>Installing</h2>
To install package click on the smartmontools.pkg icon and follow installation process. Files will be installed to the <b>/usr/local/</b> directory.
<h2>Usage</h2>
If you are having trouble understanding the output of smartctl or smartd, please first read the manual pages installed on your system:
<pre>
man 8 smartctl
man 8 smartd
man 8 update-smart-drivedb
man 5 smartd.conf
</pre>
To use smartmontools with USB drives please download and install
<a href="https://github.com/kasbert/OS-X-SAT-SMART-Driver">Max OS X kernel driver for providing access to external drive SMART data</a>. SAT SMART Driver is a free open source project (published under Apple Public Source License) by Jarkko Sonninen.
If you are using OS X El Capitan 10.11+ it is recommended to use signed version available from <a href="http://binaryfruit.com/drivedx/usb-drive-support/">DriveDx web site</a>.
<p>
More information could be found on the <a href="https://www.smartmontools.org">www.smartmontools.org</a> website.
<h2>Uninstalling</h2>
If you want to uninstall already installed package run <tt>'sudo smart-pkg-uninstall'</tt> in the terminal.
</body>
</html>

%package bin
Summary: bin components for the smartmontools package.
Group: Binaries
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}

%description bin
bin components for the smartmontools package.


%package data
Summary: data components for the smartmontools package.
Group: Data

%description data
data components for the smartmontools package.


%package doc
Summary: doc components for the smartmontools package.
Group: Documentation
Requires: smartmontools-man = %{version}-%{release}

%description doc
doc components for the smartmontools package.


%package license
Summary: license components for the smartmontools package.
Group: Default

%description license
license components for the smartmontools package.


%package man
Summary: man components for the smartmontools package.
Group: Default

%description man
man components for the smartmontools package.


%package services
Summary: services components for the smartmontools package.
Group: Systemd services

%description services
services components for the smartmontools package.


%prep
%setup -q -n smartmontools-7.1
cd %{_builddir}/smartmontools-7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578332342
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1578332342
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/smartmontools
cp %{_builddir}/smartmontools-7.1/COPYING %{buildroot}/usr/share/package-licenses/smartmontools/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smartctl
/usr/bin/smartd
/usr/bin/update-smart-drivedb

%files data
%defattr(-,root,root,-)
/usr/share/smartmontools/drivedb.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/smartmontools/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/smartmontools/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/smartd.conf.5
/usr/share/man/man8/smartctl.8
/usr/share/man/man8/smartd.8
/usr/share/man/man8/update-smart-drivedb.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/smartd.service
