#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBF0B339C64BCAA8B (smartmontools-support@listi.jpberlin.de)
#
Name     : smartmontools
Version  : 7.2
Release  : 13
URL      : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.2/smartmontools-7.2.tar.gz
Source0  : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.2/smartmontools-7.2.tar.gz
Source1  : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.2/smartmontools-7.2.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: smartmontools-bin = %{version}-%{release}
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-man = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}
BuildRequires : libcap-ng-dev
BuildRequires : systemd-dev

%description
==========================================================
smartmontools - S.M.A.R.T. utility toolset for Darwin/Mac
OSX, FreeBSD, Linux, NetBSD, OpenBSD, Solaris, and Windows.
==========================================================

%package bin
Summary: bin components for the smartmontools package.
Group: Binaries
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}

%description bin
bin components for the smartmontools package.


%package data
Summary: data components for the smartmontools package.
Group: Data

%description data
data components for the smartmontools package.


%package doc
Summary: doc components for the smartmontools package.
Group: Documentation
Requires: smartmontools-man = %{version}-%{release}

%description doc
doc components for the smartmontools package.


%package license
Summary: license components for the smartmontools package.
Group: Default

%description license
license components for the smartmontools package.


%package man
Summary: man components for the smartmontools package.
Group: Default

%description man
man components for the smartmontools package.


%package services
Summary: services components for the smartmontools package.
Group: Systemd services

%description services
services components for the smartmontools package.


%prep
%setup -q -n smartmontools-7.2
cd %{_builddir}/smartmontools-7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609884244
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1609884244
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/smartmontools
cp %{_builddir}/smartmontools-7.2/COPYING %{buildroot}/usr/share/package-licenses/smartmontools/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smartctl
/usr/bin/smartd
/usr/bin/update-smart-drivedb

%files data
%defattr(-,root,root,-)
/usr/share/smartmontools/drivedb.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/smartmontools/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/smartmontools/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/smartd.conf.5
/usr/share/man/man8/smartctl.8
/usr/share/man/man8/smartd.8
/usr/share/man/man8/update-smart-drivedb.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/smartd.service
