#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x18ECDA46CBF6BAC6 (smartmontools-support@listi.jpberlin.de)
#
Name     : smartmontools
Version  : 7.0
Release  : 11
URL      : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.0/smartmontools-7.0.tar.gz
Source0  : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.0/smartmontools-7.0.tar.gz
Source99 : https://sourceforge.net/projects/smartmontools/files/smartmontools/7.0/smartmontools-7.0.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: smartmontools-bin = %{version}-%{release}
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-man = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}
BuildRequires : libcap-ng-dev
BuildRequires : systemd-dev

%description
==========================================================
smartmontools - S.M.A.R.T. utility toolset for Darwin/Mac
OSX, FreeBSD, Linux, NetBSD, OpenBSD, Solaris, and Windows.
==========================================================

%package bin
Summary: bin components for the smartmontools package.
Group: Binaries
Requires: smartmontools-data = %{version}-%{release}
Requires: smartmontools-license = %{version}-%{release}
Requires: smartmontools-man = %{version}-%{release}
Requires: smartmontools-services = %{version}-%{release}

%description bin
bin components for the smartmontools package.


%package data
Summary: data components for the smartmontools package.
Group: Data

%description data
data components for the smartmontools package.


%package doc
Summary: doc components for the smartmontools package.
Group: Documentation
Requires: smartmontools-man = %{version}-%{release}

%description doc
doc components for the smartmontools package.


%package license
Summary: license components for the smartmontools package.
Group: Default

%description license
license components for the smartmontools package.


%package man
Summary: man components for the smartmontools package.
Group: Default

%description man
man components for the smartmontools package.


%package services
Summary: services components for the smartmontools package.
Group: Systemd services

%description services
services components for the smartmontools package.


%prep
%setup -q -n smartmontools-7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546195887
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1546195887
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/smartmontools
cp COPYING %{buildroot}/usr/share/package-licenses/smartmontools/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smartctl
/usr/bin/smartd
/usr/bin/update-smart-drivedb

%files data
%defattr(-,root,root,-)
/usr/share/smartmontools/drivedb.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/smartmontools/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/smartmontools/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/smartd.conf.5
/usr/share/man/man8/smartctl.8
/usr/share/man/man8/smartd.8
/usr/share/man/man8/update-smart-drivedb.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/smartd.service
